sudo: required
language: python
dist: trusty
services:
- docker
before_script:
- docker --version
- docker-compose --version
script:
- chmod -R 0777 ./home
- docker-compose build
- docker images
- docker-compose up -d
- docker ps
- sleep 10
- chmod ugo+x tests/test_php.sh && bash tests/test_php.sh
- chmod ugo+x tests/test_python.sh && bash tests/test_python.sh
- chmod ugo+x tests/test_nodejs.sh && bash tests/test_nodejs.sh
