version: '3'

services:
    jenkins:
        container_name: fullstack_jenkins
        build:
            context: ./jenkins-alpine
        image: vietdien2005/fullstack_jenkins_alpine:latest
        volumes:
            - ./home:/var/jenkins_home
        environment:
            JAVA_OPTS: -Djenkins.install.runSetupWizard=false
        ports:
            - "8888:8080"
            - "50000:50000"
        dns:
            - 8.8.8.8
            - 8.8.4.4