version: '2'

services:
    jenkins:
        build: 
            context: ./jenkins-alpine
        image: vietdien2005/fullstack_jenkins_alpine_minimal:latest
        volumes:
            - ./home:/var/jenkins_home
        ports:
            - "8888:8080"
            - "50000:50000"
        dns:
            - 8.8.8.8
            - 8.8.4.4