version: '2'

services:
    jenkins:
        build: 
            context: ./jenkins
        image: vietdien2005/fullstack_jenkins:latest
        volumes:
            - ./jenkins/home:/var/jenkins_home
        ports:
            - "8080:8080"
            - "50000:50000"
        dns:
            - 8.8.8.8
            - 8.8.4.4